
# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Run deploy script
        run: |
          pwd
          ls
          sudo ./scripts/deploy.sh
        shell: bash
