name: CICD via Docker Hub to Raspberry Pi

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/personal-website:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: SSH Remote Commands
#        uses: appleboy/ssh-action@v0.1.4
#        with:
#          host:
#          username: ${{ secrets.PI_USERNAME }}
#          password: ${{ secrets.PI_PASSWORD }}
#          script:  docker ps
